# Generated by Django 3.0.3 on 2020-02-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='op_verv',
        ),
        migrations.AddField(
            model_name='option',
            name='num',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
